---
title: "Analyze MASSpy Output"
author: "Alicia Key"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the libraries

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)
```

## Set a plot theme

```{r}
theme_set(theme_linedraw())
```

## Load the data

```{r}
flux_sol <- read_csv(here("input", "flux_sol.csv"))
conc_sol <- read_csv(here("input", "conc_sol.csv"))
```

## Display head of the data

```{r}
head(flux_sol)
```

```{r}
head(conc_sol)
```

## Flux Operations

This section will operate on the fluxes of the reactions dataframe.

### Pivot longer

```{r}
flux_long <- flux_sol %>%
  pivot_longer(-Time, names_to = "flux", values_to = "mM_per_hr")

head(flux_long)
```

### Find CVs of all fluxes

```{r}
flux_stats <- flux_long %>%
  group_by(flux) %>%
  summarize(cv = sd(mM_per_hr) / mean(mM_per_hr)) %>%
  arrange(desc(cv))

head(flux_stats, n = 5)
```

### Plot the Top 5 Fluxes

```{r}
top_5_fluxes <- head(flux_stats$flux, n = 5)

flux_long %>%
  filter(flux %in% top_5_fluxes) %>%
  ggplot(aes(x = Time, y = mM_per_hr, color = flux)) +
  geom_line()
```

## Concentration Operations

This operates on the concentrations of metabolite dataframe.

### Pivot longer

```{r}
conc_long <- conc_sol %>%
  pivot_longer(-Time, names_to = "metabolite", values_to = "mM")

head(conc_long)
```

### Order by descending CV

```{r}
conc_stats <- conc_long %>%
  group_by(metabolite) %>%
  summarize(cv = sd(mM) / mean(mM)) %>%
  arrange(desc(cv))

head(conc_stats, n = 5)
```
### Plot the metabolites

```{r}
top_5_metabolites <- head(conc_stats$metabolite, n = 2)

conc_long %>%
  filter(metabolite %in% top_5_metabolites) %>%
  ggplot(aes(x = Time, y = mM, color = metabolite)) +
  geom_line() +
  scale_x_log10()
```
