---
title: "Third Draft"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Functions

This will also load the parts of the tidyverse we need.

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(doParallel)
source("simulation_functions.R")
```

## Make a theme for the plots

```{r}
theme_set(
  theme_linedraw() +
    theme(
      plot.title = element_text(size = 18, face = "bold"),
      axis.title = element_text(size = 12, face = "bold"),
      axis.text = element_text(size = 9)
    )
)
```

## Setup Initial Conditions

```{r}
initial_condition_df <- cross_initial_conditions(
  x1 = c(0.75, 1, 1.25),
  x2 = c(0.75, 1, 1.25),
  x3 = c(0.75, 1, 1.25),
  x4 = c(0.75, 1, 1.25),
  x5 = c(0.75, 1, 1.25)
)
```

## Turn Each Row Into a Vector

```{r}
run_specs <- vector(mode = "list", length = nrow(initial_condition_df))

serial <- 1

for (i in 1:nrow(initial_condition_df)) {
  initial_condition_vec <- vector(mode = "numeric", length = length(initial_condition_df))
  
  initial_condition_vec[1] <- initial_condition_df[i, "x1"]
  initial_condition_vec[2] <- initial_condition_df[i, "x2"]
  initial_condition_vec[3] <- initial_condition_df[i, "x3"]
  initial_condition_vec[4] <- initial_condition_df[i, "x4"]
  initial_condition_vec[5] <- initial_condition_df[i, "x5"]
  
  run_specs[[i]] <- vector(mode = "list", length = 2)
  run_specs[[i]][["ics"]] <- initial_condition_vec
  run_specs[[i]][["run_name"]] <- paste("run", serial, sep = "_")
  
  serial <- serial + 1
}
```

## Use doParallel to Create All Plots

```{r}
# cl <- makeCluster(3, type='PSOCK')
cl <- makeCluster(4, type='PSOCK')
registerDoParallel(cl)

initial_condition_plots <- foreach(i=1:length(run_specs), .packages = "tidyverse") %dopar% {
  initial_conditions_run_and_plot(
    run_name = run_specs[[i]][["run_name"]],
    x1_initial = run_specs[[i]][["ics"]][[1]],
    x2_initial = run_specs[[i]][["ics"]][[2]],
    x3_initial = run_specs[[i]][["ics"]][[3]],
    x4_initial = run_specs[[i]][["ics"]][[4]],
    x5_initial = run_specs[[i]][["ics"]][[5]]
  )
}

# turn parallel processing off and run sequentially again:
registerDoSEQ()
```

## Try One of the Plots?

```{r}
initial_condition_plots[[100]][["simulation_plot"]]
```
